stages:
    - build
    - test
    - deploy staging
#    - test staging
    - deploy production
#    - test production

variables:
#    APP_BASE_URL: http://melvin-20220707.s3-website-us-east-1.amazonaws.com
#    APP_BASE_URL_STAGING: http://melvin-20220707-staging.s3-website-us-east-1.amazonaws.com
     APP_VERSION: $CI_PIPELINE_IID
    
build website:
    image: node:16-alpine
    stage: build
    script:
        - yarn install
        - yarn lint
        - yarn test
        - yarn build
        - echo $APP_VERSION > build/version.html
    artifacts:
        paths:
            - build

test website:
    image: node:16-alpine
    stage: test
    script:
        - yarn global add serve
        - apk add curl
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000 | grep "React App"

.deploy:
#    stage: deploy staging
#    environment: staging
    image: 
        name: amazon/aws-cli:2.7.20
        entrypoint: [""]
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    script:
        - aws --version
#        - aws s3 sync build s3://$AWS_S3_BUCKET_STAGING --delete
        - aws s3 sync build s3://$AWS_S3_BUCKET --delete
#        - curl $APP_BASE_URL_STAGING | grep "React App" 
        - curl $CI_ENVIRONMENT_URL | grep "React App"
        - curl $CI_ENVIRONMENT_URL/version.html | grep $APP_VERSION

deploy to staging:
    stage: deploy staging
    when: manual
    environment: staging
    extends: .deploy
#    image: 
#        name: amazon/aws-cli:2.7.20
#        entrypoint: [""]
#    rules:
#        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#    script:
#        - aws --version
#        - aws s3 sync build s3://$AWS_S3_BUCKET_STAGING --delete
#        - aws s3 sync build s3://$AWS_S3_BUCKET --delete
#        - curl $APP_BASE_URL_STAGING | grep "React App" 
#        - curl $CI_ENVIRONMENT_URL | grep "React App"

#staging tests:
#    stage: test staging
#    image: curlimages/curl
#    rules:
#        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#    script:
#        - curl $APP_BASE_URL_STAGING | grep "React App"

deploy to production:
    stage: deploy production
    environment: production
    extends: .deploy
#    image: 
#        name: amazon/aws-cli:2.7.20
#        entrypoint: [""]
#    rules:
#        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#    script:
#        - aws --version
#        - aws s3 sync build s3://$AWS_S3_BUCKET --delete
#        - curl $CI_ENVIRONMENT_URL | grep "React App"

#production tests:
#    stage: test production
#    image: curlimages/curl
#    rules:
#        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#    script:
#        - curl $APP_BASE_URL | grep "React App"
